import { GalleryVerticalEnd } from "lucide-react"
import Link from "next/link"
import { CONSTANTS } from "@/lib/constants"
import { FooterAgreement } from "@/components/footer-agreement"

//     import type { Metadata } from "next"
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="flex min-h-svh flex-col items-center justify-center gap-6 bg-muted p-6 md:p-10">
      <div className="flex w-full max-w-sm flex-col gap-6">
        <Link
          href="/"
          className="flex items-center gap-2 self-center font-medium"
        >
          <div className="flex h-6 w-6 items-center justify-center rounded-md bg-primary text-primary-foreground">
            <GalleryVerticalEnd className="size-4" />
          </div>
          {CONSTANTS.APP_NAME}
        </Link>
        <div className="flex flex-col gap-6">{children}</div>
        <FooterAgreement />
      </div>
    </div>
  )
}
